### ISSUE TITLE
links shortcut

### ISSUE THREAD

**Issue by lephtHanded** [u-alexey/seafile_ce-edition_dark_theme#1]
hey, great theme...
somethings happening that i don't understand though...
the #links shortcut doesn't appear with this theme, [here's the issue](https://forum.seafile.com/t/external-share-link-listing/18602)

**Comment by udlch** [comment]
Hi, @lephtHanded. I don't use Seafile anymore, and this project a little bit dead. Please try [this repo](https://github.com/6bIBAET/seafile-8.0.2-dark-theme) instead.

**Comment by lephtHanded** [comment]
thank you
